export const ALERT_CLIENT_CLEAR = 'ALERT/CLIENT/CLEAR'
export const ALERT_CLIENT_ERROR = 'ALERT/CLIENT/ERROR'

export const APP_SAKSBEHANDLER_GET_REQUEST = 'APP/SAKSBEHANDLER/GET/REQUEST'
export const APP_SAKSBEHANDLER_GET_SUCCESS = 'APP/SAKSBEHANDLER/GET/SUCCESS'
export const APP_SAKSBEHANDLER_GET_FAILURE = 'APP/SAKSBEHANDLER/GET/FAILURE'
export const APP_SERVERINFO_GET_REQUEST = 'APP/SERVERINFO/GET/REQUEST'
export const APP_SERVERINFO_GET_SUCCESS = 'APP/SERVERINFO/GET/SUCCESS'
export const APP_SERVERINFO_GET_FAILURE = 'APP/SERVERINFO/GET/FAILURE'
export const APP_ENHETER_GET_REQUEST = 'APP/ENHETER/GET/REQUEST'
export const APP_ENHETER_GET_SUCCESS = 'APP/ENHETER/GET/SUCCESS'
export const APP_ENHETER_GET_FAILURE = 'APP/ENHETER/GET/FAILURE'
export const APP_UTGAARDATO_GET_REQUEST = 'APP/UTGAARDATO/GET/REQUEST'
export const APP_UTGAARDATO_GET_SUCCESS = 'APP/UTGAARDATO/GET/SUCCESS'
export const APP_UTGAARDATO_GET_FAILURE = 'APP/UTGAARDATO/GET/FAILURE'
export const APP_LOGMEAGAIN_GET_REQUEST = 'APP/LOGMEAGAIN/GET/REQUEST'
export const APP_LOGMEAGAIN_GET_SUCCESS = 'APP/LOGMEAGAIN/GET/SUCCESS'
export const APP_LOGMEAGAIN_GET_FAILURE = 'APP/LOGMEAGAIN/GET/FAILURE'
export const APP_CLEAN_DATA = 'APP/CLEAN_DATA'

export const FORM_VALUE_SET = 'FORM/VALUE/SET'
export const FORM_ARBEIDSFORHOLD_ADD = 'FORM/ARBEIDSFORHOLD/ADD'
export const FORM_ARBEIDSFORHOLD_REMOVE = 'FORM/ARBEIDSFORHOLD/REMOVE'
export const FORM_FAMILIERELASJONER_ADD = 'FORM/FAMILIERELASJONER/ADD'
export const FORM_FAMILIERELASJONER_REMOVE = 'FORM/FAMILIERELASJONER/REMOVE'
export const FORM_ABROADPERSON_ADD_FAILURE = 'FORM/ABROADPERSON/ADD/FAILURE'
export const FORM_ABROADPERSON_ADD_SUCCESS = 'FORM/ABROADPERSON/ADD/SUCCESS'
export const FORM_TPSPERSON_ADD_FAILURE = 'FORM/TPSPERSON/ADD/FAILURE'
export const FORM_TPSPERSON_ADD_SUCCESS = 'FORM/TPSPERSON/ADD/SUCCESS'

export const SAK_ARBEIDSFORHOLD_GET_REQUEST = 'SAK/ARBEIDSFORHOLD/GET/REQUEST'
export const SAK_ARBEIDSFORHOLD_GET_SUCCESS = 'SAK/ARBEIDSFORHOLD/GET/SUCCESS'
export const SAK_ARBEIDSFORHOLD_GET_FAILURE = 'SAK/ARBEIDSFORHOLD/GET/FAILURE'
export const SAK_FAGSAKER_GET_REQUEST = 'SAK/FAGSAKER/GET/REQUEST'
export const SAK_FAGSAKER_GET_SUCCESS = 'SAK/FAGSAKER/GET/SUCCESS'
export const SAK_FAGSAKER_GET_FAILURE = 'SAK/FAGSAKER/GET/FAILURE'
export const SAK_FAGSAKER_RESET = 'SAK/FAGSAKER/RESET'
export const SAK_INSTITUSJONER_GET_REQUEST = 'SAK/INSTITUSJONER/GET/REQUEST'
export const SAK_INSTITUSJONER_GET_SUCCESS = 'SAK/INSTITUSJONER/GET/SUCCESS'
export const SAK_INSTITUSJONER_GET_FAILURE = 'SAK/INSTITUSJONER/GET/FAILURE'
export const SAK_LANDKODER_GET_REQUEST = 'SAK/LANDKODER/GET/REQUEST'
export const SAK_LANDKODER_GET_SUCCESS = 'SAK/LANDKODER/GET/SUCCESS'
export const SAK_LANDKODER_GET_FAILURE = 'SAK/LANDKODER/GET/FAILURE'
export const SAK_PERSON_GET_REQUEST = 'SAK/PERSON/GET/REQUEST'
export const SAK_PERSON_GET_SUCCESS = 'SAK/PERSON/GET/SUCCESS'
export const SAK_PERSON_GET_FAILURE = 'SAK/PERSON/GET/FAILURE'
export const SAK_PERSON_RELATERT_GET_REQUEST =
  'SAK/PERSON/RELATERT/GET/REQUEST'
export const SAK_PERSON_RELATERT_GET_SUCCESS =
  'SAK/PERSON/RELATERT/GET/SUCCESS'
export const SAK_PERSON_RELATERT_GET_FAILURE =
  'SAK/PERSON/RELATERT/GET/FAILURE'
export const SAK_PERSON_RESET = 'SAK/PERSON/RESET'
export const SAK_PERSON_RELATERT_RESET = 'SAK/PERSON/RELATERT/RESET'
export const SAK_SEND_POST_REQUEST = 'SAK/SEND/POST/REQUEST'
export const SAK_SEND_POST_SUCCESS = 'SAK/SEND/POST/SUCCESS'
export const SAK_SEND_POST_FAILURE = 'SAK/SEND/POST/FAILURE'
export const SAK_PRELOAD = 'SAK/PRELOAD'

export const SVARPASED_SEDS_GET_REQUEST =
  'SVARPASED/SEDS/GET/REQUEST'
export const SVARPASED_SEDS_GET_SUCCESS =
  'SVARPASED/SEDS/GET/SUCCESS'
export const SVARPASED_SEDS_GET_FAILURE =
  'SVARPASED/SEDS/GET/FAILURE'
export const SVARPASED_FAMILIERELASJONER_ADD =
  'SVARPASED/FAMILIERELASJONER_ADD/'
export const SVARPASED_FAMILIERELASJONER_REMOVE =
  'SVARPASED/FAMILIERELASJONER_REMOVE/GET/'

export const SVARPASED_ARBEIDSFORHOLD_ADD = 'SVARPASED/ARBEIDSFORHOLD/ADD'
export const SVARPASED_ARBEIDSFORHOLD_REMOVE =
  'SVARPASED/ARBEIDSFORHOLD/REMOVE'

export const SVARPASED_PERSON_GET_REQUEST = 'SVARPASED/PERSON/GET/REQUEST'
export const SVARPASED_PERSON_GET_SUCCESS = 'SVARPASED/PERSON/GET/SUCCESS'
export const SVARPASED_PERSON_GET_FAILURE = 'SVARPASED/PERSON/GET/FAILURE'

export const SVARPASED_PERSON_RELATERT_GET_REQUEST =
  'SVARPASED/PERSON/RELATERT/GET/REQUEST'
export const SVARPASED_PERSON_RELATERT_GET_SUCCESS =
  'SVARPASED/PERSON/RELATERT/GET/SUCCESS'
export const SVARPASED_PERSON_RELATERT_GET_FAILURE =
  'SVARPASED/PERSON/RELATERT/GET/FAILURE'

export const SVARPASED_SET_SED = 'SVARPASED/SET/SED'

export const SVARPASED_SENDSVARPASEDDATA = 'SVARPASED/SENDSVARPASEDDAT'
export const SVARPASED_SENDSVARPASEDDATA_POST_REQUEST =
  'SVARPASED/SENDSVARPASEDDATA/POST/REQUEST'
export const SVARPASED_SENDSVARPASEDDATA_POST_SUCCESS =
  'SVARPASED/SENDSVARPASEDDATA/POST/SUCCESS'
export const SVARPASED_SENDSVARPASEDDATA_POST_FAILURE =
  'SVARPASED/SENDSVARPASEDDATA/POST/FAILURE'

export const SVARPASED_PERSON_RELATERT_RESET =
  'SVARPASED/PERSON/RELATERT/RESET'
export const SVARPASED_TPSPERSON_ADD_FAILURE =
  'SVARPASED/TPSPERSON/ADD/FAILURE'
export const SVARPASED_TPSPERSON_ADD_SUCCESS =
  'SVARPASED/TPSPERSON/ADD/SUCCESS'

export const SVARPASED_ARBEIDSFORHOLD_GET_REQUEST =
  'SVARPASED/ARBEIDSFORHOLD/GET/REQUEST'
export const SVARPASED_ARBEIDSFORHOLD_GET_SUCCESS =
  'SVARPASED/ARBEIDSFORHOLD/GET/SUCCESS'
export const SVARPASED_ARBEIDSFORHOLD_GET_FAILURE =
  'SVARPASED/ARBEIDSFORHOLD/GET/FAILURE'

export const SVARPASED_INNTEKT_GET_REQUEST = 'SVARPASED/INNTEKT/GET/REQUEST'
export const SVARPASED_INNTEKT_GET_SUCCESS = 'SVARPASED/INNTEKT/GET/SUCCESS'
export const SVARPASED_INNTEKT_GET_FAILURE = 'SVARPASED/INNTEKT/GET/FAILURE'

export const SVARPASED_SELECTED_INNTEKT_REQUEST =
  'SVARPASED/SELECTED/INNTEKT/REQUEST'
export const SVARPASED_SELECTED_INNTEKT_SUCCESS =
  'SVARPASED/SELECTED/INNTEKT/SUCCESS'
export const SVARPASED_SELECTED_INNTEKT_FAILURE =
  'SVARPASED/SELECTED/INNTEKT/FAILURE'

export const SERVER_INTERNAL_ERROR = 'SERVER/INTERNAL/ERROR'
export const SERVER_UNAUTHORIZED_ERROR = 'SERVER/UNAUTHORIZED/ERROR'

export const UI_MODAL_SET = 'UI/MODAL/SET'
export const UI_HIGHCONTRAST_TOGGLE = 'UI/HIGHCONTRAST/TOGGLE'

export const VEDLEGG_DOKUMENT_GET_REQUEST = 'VEDLEGG/DOKUMENT/GET/REQUEST'
export const VEDLEGG_DOKUMENT_GET_SUCCESS = 'VEDLEGG/DOKUMENT/GET/SUCCESS'
export const VEDLEGG_DOKUMENT_GET_FAILURE = 'VEDLEGG/DOKUMENT/GET/FAILURE'
export const VEDLEGG_POST_REQUEST = 'VEDLEGG/POST/REQUEST'
export const VEDLEGG_POST_SUCCESS = 'VEDLEGG/POST/SUCCESS'
export const VEDLEGG_POST_FAILURE = 'VEDLEGG/POST/FAILURE'
export const VEDLEGG_VALUE_SET = 'VEDLEGG/VALUE/SET'
