export const SERVER_INTERNAL_ERROR = 'SERVER/INTERNAL/ERROR'
export const SERVER_UNAUTHORIZED_ERROR = 'SERVER/UNAUTHORIZED/ERROR'

export const ALERT_CLIENT_CLEAR = 'ALERT/CLIENT/CLEAR'
export const ALERT_CLIENT_ERROR = 'ALERT/CLIENT/ERROR'

export const UI_MODAL_SET = 'UI/MODAL/SET'
export const UI_HIGHCONTRAST_TOGGLE = 'UI/HIGHCONTRAST/TOGGLE'
